package com.nf147.ssm.entity;

public class Apiresponse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiresponse.apiResponse_code
     *
     * @mbg.generated
     */
    private Integer apiresponseCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiresponse.apiResponse_type
     *
     * @mbg.generated
     */
    private String apiresponseType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apiresponse.apiResponse_message
     *
     * @mbg.generated
     */
    private String apiresponseMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiresponse.apiResponse_code
     *
     * @return the value of apiresponse.apiResponse_code
     *
     * @mbg.generated
     */
    public Integer getApiresponseCode() {
        return apiresponseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiresponse.apiResponse_code
     *
     * @param apiresponseCode the value for apiresponse.apiResponse_code
     *
     * @mbg.generated
     */
    public void setApiresponseCode(Integer apiresponseCode) {
        this.apiresponseCode = apiresponseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiresponse.apiResponse_type
     *
     * @return the value of apiresponse.apiResponse_type
     *
     * @mbg.generated
     */
    public String getApiresponseType() {
        return apiresponseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiresponse.apiResponse_type
     *
     * @param apiresponseType the value for apiresponse.apiResponse_type
     *
     * @mbg.generated
     */
    public void setApiresponseType(String apiresponseType) {
        this.apiresponseType = apiresponseType == null ? null : apiresponseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apiresponse.apiResponse_message
     *
     * @return the value of apiresponse.apiResponse_message
     *
     * @mbg.generated
     */
    public String getApiresponseMessage() {
        return apiresponseMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apiresponse.apiResponse_message
     *
     * @param apiresponseMessage the value for apiresponse.apiResponse_message
     *
     * @mbg.generated
     */
    public void setApiresponseMessage(String apiresponseMessage) {
        this.apiresponseMessage = apiresponseMessage == null ? null : apiresponseMessage.trim();
    }
}