package com.nf147.ssm.entity;

public class Photo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_id
     *
     * @mbg.generated
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.photo_name
     *
     * @mbg.generated
     */
    private String photoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo.pet_id
     *
     * @mbg.generated
     */
    private Integer petId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_id
     *
     * @return the value of photo.photo_id
     *
     * @mbg.generated
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_id
     *
     * @param photoId the value for photo.photo_id
     *
     * @mbg.generated
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.photo_name
     *
     * @return the value of photo.photo_name
     *
     * @mbg.generated
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.photo_name
     *
     * @param photoName the value for photo.photo_name
     *
     * @mbg.generated
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName == null ? null : photoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo.pet_id
     *
     * @return the value of photo.pet_id
     *
     * @mbg.generated
     */
    public Integer getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo.pet_id
     *
     * @param petId the value for photo.pet_id
     *
     * @mbg.generated
     */
    public void setPetId(Integer petId) {
        this.petId = petId;
    }
}